# Numpy Tutorial

In [12]:
import numpy as np
a = np.empty((2, 3))
a, a.shape, type(a), a[0], a[-1][-1], a[0][0]

(array([[0., 0., 0.],
        [0., 0., 0.]]),
 (2, 3),
 numpy.ndarray,
 array([0., 0., 0.]),
 0.0,
 0.0)

In [16]:
np.arange(23)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22])

# array of even and odd numbers.

In [18]:
even = np.arange(0, 23, 2)
even

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [19]:
odd = np.arange(1, 23, 2)
odd

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21])

In [20]:
np.arange(0, 23, 3)

array([ 0,  3,  6,  9, 12, 15, 18, 21])

In [21]:
np.arange(0, 23, 0.5)

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5,
       11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5, 16. ,
       16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5, 20. , 20.5, 21. , 21.5,
       22. , 22.5])

# Linear Space=linspace (SHOWS linear relation/trend)

In [22]:
lin = np.linspace(0, 20, 10)
lin

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [24]:
lin = np.linspace(0, -20, 10)
lin, lin.dtype

(array([  0.        ,  -2.22222222,  -4.44444444,  -6.66666667,
         -8.88888889, -11.11111111, -13.33333333, -15.55555556,
        -17.77777778, -20.        ]),
 dtype('float64'))

# define the data type of array

In [25]:
x = np.ones(2, dtype=np.int64)
x

array([1, 1], dtype=int64)

In [27]:
y = np.arange(10, dtype=np.float64)
y, y.dtype

(array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]), dtype('float64'))

In [28]:
z = np.arange(10, 20, 0.5, dtype=np.float64)
z, z.dtype

(array([10. , 10.5, 11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. ,
        15.5, 16. , 16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5]),
 dtype('float64'))

In [34]:
z1 = np.arange(0, 30.7, 0.5)
z1, z1.dtype

(array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
         5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5,
        11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5, 16. ,
        16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5, 20. , 20.5, 21. , 21.5,
        22. , 22.5, 23. , 23.5, 24. , 24.5, 25. , 25.5, 26. , 26.5, 27. ,
        27.5, 28. , 28.5, 29. , 29.5, 30. , 30.5]),
 dtype('float64'))

In [35]:
z1 = np.arange(0, 30.7, 0.5, dtype=np.int64)
z1, z1.dtype

(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64),
 dtype('int64'))

# Assingment: Differene between int32, 64 or float32 and float64.

In [46]:
# sorting an array.
a = np.random.randint(10, 100, 11)
print(f'array a:',a)
b = np.sort(a)
print(f'sorted array b:',b)

array a: [61 68 70 68 44 13 48 48 36 27 57]
sorted array b: [13 27 36 44 48 48 57 61 68 68 70]


In [50]:
d = np.random.randint(1, 110, 11 )
print(d)
t  = np.sort(d)
print(t)
e = np.argsort(d)
e

[50 57 50 37 70 14  9 77 96 18 16]
[ 9 14 16 18 37 50 50 57 70 77 96]


array([ 6,  5, 10,  9,  3,  0,  2,  1,  4,  7,  8], dtype=int64)

In [54]:
# ID array concatenation.
a = np.random.randint(1, 100, 11)
b = np.random.randint(1, 100, 11)
d = np.concatenate((a, b))
a, b, d


(array([68, 63, 64, 66, 88,  7, 11, 55, 74, 19, 68]),
 array([ 2, 18, 97, 22, 32, 62, 93, 19, 93, 73, 67]),
 array([68, 63, 64, 66, 88,  7, 11, 55, 74, 19, 68,  2, 18, 97, 22, 32, 62,
        93, 19, 93, 73, 67]))

# To concatenate the arrays row wise the number of Columns must be same.

In [59]:
# 2D array concatenation. (Row wise)
a = np.random.randint(1, 100, (2,3))
b = np.random.randint(1, 100, (3,3))
d = np.concatenate((a, b))
a, b, d


(array([[33, 57, 24],
        [20, 39, 85]]),
 array([[75, 84, 46],
        [21,  4, 37],
        [44, 66, 58]]),
 array([[33, 57, 24],
        [20, 39, 85],
        [75, 84, 46],
        [21,  4, 37],
        [44, 66, 58]]))

In [63]:
# 2D array concatenation. (Column wise)
a = np.random.randint(1, 100, (3,2))
b = np.random.randint(1, 100, (3,3))
d = np.concatenate((a, b), axis=1)
a, b, d


(array([[24,  4],
        [ 9, 52],
        [34, 47]]),
 array([[14, 41, 67],
        [97, 52,  7],
        [ 1, 24, 39]]),
 array([[24,  4, 14, 41, 67],
        [ 9, 52, 97, 52,  7],
        [34, 47,  1, 24, 39]]))

In [64]:
d.ndim

2

In [73]:
# 3D arrays.
a = np.random.randint(1, 100, (3,2,4))
a, a.ndim, len(a), a.size, a.dtype, a.shape

(array([[[11,  6, 52, 52],
         [95, 32, 26, 28]],
 
        [[94, 92, 59, 55],
         [16, 10, 79, 16]],
 
        [[88, 89, 52, 63],
         [20, 52, 38, 14]]]),
 3,
 3,
 24,
 dtype('int32'),
 (3, 2, 4))

In [76]:
# array reshape.
a = np.random.randint(1, 100, (2,4))
b = a.reshape(4, 2)
a, b

(array([[82, 24, 30, 98],
        [ 7, 42, 23, 64]]),
 array([[82, 24],
        [30, 98],
        [ 7, 42],
        [23, 64]]))

In [77]:
# array reshape.
a = np.random.randint(1, 100, (3, 2,4))
b = a.reshape(3, 4, 2)
a, b

(array([[[30, 99, 21, 88],
         [89, 20, 54, 62]],
 
        [[43, 94, 77, 17],
         [18, 24, 75, 69]],
 
        [[13, 34, 48, 61],
         [51, 64, 82, 57]]]),
 array([[[30, 99],
         [21, 88],
         [89, 20],
         [54, 62]],
 
        [[43, 94],
         [77, 17],
         [18, 24],
         [75, 69]],
 
        [[13, 34],
         [48, 61],
         [51, 64],
         [82, 57]]]))

In [79]:
# array reshape.
a = np.random.randint(1, 100, (3, 2,4))
b = a.reshape(1, 4, 6)
a, b, a.ndim, b.ndim

(array([[[49, 40, 75,  9],
         [92, 70, 57, 65]],
 
        [[56, 33, 82, 41],
         [58, 52, 11, 90]],
 
        [[69, 51, 26, 44],
         [64, 98,  2, 86]]]),
 array([[[49, 40, 75,  9, 92, 70],
         [57, 65, 56, 33, 82, 41],
         [58, 52, 11, 90, 69, 51],
         [26, 44, 64, 98,  2, 86]]]),
 3,
 3)

In [87]:
# converting 1D into 2D.
a = np.random.randint(1, 100, 11)
b = a[np.newaxis, :]
a, a.ndim, a.size, a.shape, b, b.ndim, b.size, b.shape

(array([76, 55, 84, 46, 81, 71, 56, 46, 19, 12, 91]),
 1,
 11,
 (11,),
 array([[76, 55, 84, 46, 81, 71, 56, 46, 19, 12, 91]]),
 2,
 11,
 (1, 11))

In [89]:
# converting 1D into 2D.
a = np.random.randint(1, 100, 11)
b = a[:, np.newaxis]
a, a.ndim, a.size, a.shape, b, b.ndim, b.size, b.shape

(array([14, 11, 77,  7, 45, 57, 59, 79,  8, 73, 24]),
 1,
 11,
 (11,),
 array([[14],
        [11],
        [77],
        [ 7],
        [45],
        [57],
        [59],
        [79],
        [ 8],
        [73],
        [24]]),
 2,
 11,
 (11, 1))

# Indexing and Slicing.

In [94]:
a = np.random.randint(1,11, 8)
a

array([6, 9, 7, 7, 5, 2, 3, 1])

In [95]:
a[2]

7

In [97]:
a[1:7]

array([9, 7, 7, 5, 2, 3])

In [98]:
a[-4]

5

In [99]:
a[-4:]

array([5, 2, 3, 1])

In [100]:
a[5:]

array([2, 3, 1])

In [101]:
a[:5]

array([6, 9, 7, 7, 5])

In [102]:
a[3::]

array([7, 5, 2, 3, 1])

In [103]:
a[3:]

array([7, 5, 2, 3, 1])

In [105]:
b= np.random.randint(1, 11, (3, 4))
b

array([[3, 1, 9, 9],
       [6, 2, 9, 6],
       [6, 2, 7, 1]])

In [106]:
b[0]

array([3, 1, 9, 9])

In [107]:
b[1:]

array([[6, 2, 9, 6],
       [6, 2, 7, 1]])

In [108]:
b[1:, 1:]

array([[2, 9, 6],
       [2, 7, 1]])

In [109]:
b[b < 5]

array([3, 1, 2, 2, 1])

In [110]:
b[b <= 5]

array([3, 1, 2, 2, 1])

In [111]:
b[b % 2==0]

array([6, 2, 6, 6, 2])

In [112]:
b[b % 2!=0]

array([3, 1, 9, 9, 9, 7, 1])

In [114]:
b[(b > 2) & (b > 5)]

array([9, 9, 6, 9, 6, 6, 7])

In [115]:
b[(b > 2) & (b <= 5)]

array([3])

In [116]:
b[(b > 2) & (b > 5) & b % 2==0]

array([3, 1, 6, 2, 6, 6, 2, 1])

In [117]:
b[(b > 2) | (b > 5) | b % 2==0]

array([2, 2])